### ISSUE TITLE
Switch networks within a single profile/congif/wallet

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/go-wallet#238]
As a user who uses multiple Vega networks (e.g testnet / mainnet ) I'd like to run a single wallet but switch between keys (rather than have to switch between wallets/configs. This is a expectation I have developed from using other wallets e.g Metamask.

<img width="1764" alt="Screenshot 2021-09-10 at 15 48 51" src="https://user-images.githubusercontent.com/13255539/132872748-ad8ac83d-cf2a-48c8-98c8-22fd0c819776.png">

I guess behind the scenes in metamask there is a different API end point it hits for each network.

In Vega's case I imagine something like this in the `wallet-service-config.toml`

```TOML
[Nodes: testnet]
  Hosts = [
    "n01.testnet.vega.xyz"
  ]
  Retries = 5
[Nodes: mainnet]
  Hosts = [
    "n01.vegamainnet.validator.com"
  ]
```
